# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 18:10
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180409_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_returned',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_shipped',
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=django_fsm.FSMField(default='ordered', max_length=50),
        ),
    ]
