#:kivy 1.9

BoxLayout:

  orientation: 'vertical'

  Label:
    text: 'Label'
  Button:
    text: 'Button'
  CheckBox:
    active: True
  AsyncImage:
    source: 'http://via.placeholder.com/300?text=AsyncImage'
  Slider:
    min: 0
    max: 100
    value: 73
  ProgressBar:
    min: 0
    max: 100
    progress: 34
  TextInput:
    text: 'TextInput'
  ToggleButton:
    text: 'ToggleButton'
    active: True
  Switch:
